### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by nishuoshenme** [hanbinglengyue/FART#7]
看日志调用到某个函数就crash掉了，/data/data/package-name下只有一个壳自己的dex文件
请问这种情况要怎么解决呢？使用的是x86镜像
```
10-22 05:25:06.254: D/mmap.cpp(2338): process:2338,threadid:2716 bionic/libc/bionic/mmap.cpp:mmap:null,size:262144,return addr:0x9d900000
10-22 05:25:06.298: E/AndroidRuntime(2338): FATAL EXCEPTION: Thread-141
10-22 05:25:06.298: E/AndroidRuntime(2338): Process: package-name, PID: 2338
10-22 05:25:06.298: E/AndroidRuntime(2338): java.lang.IncompatibleClassChangeError: Superclass com.tencent.bugly.yaq.proguard.j of com.tencent.bugly.yaq.proguard.as is declared final (declaration of 'com.tencent.bugly.yaq.proguard.as' appears in /data/app/package-name-1/base.apk)
10-22 05:25:06.298: E/AndroidRuntime(2338): 	at dalvik.system.DexFile.defineClassNative(Native Method)
10-22 05:25:06.298: E/AndroidRuntime(2338): 	at dalvik.system.DexFile.defineClass(DexFile.java:226)
10-22 05:25:06.298: E/AndroidRuntime(2338): 	at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
10-22 05:25:06.298: E/AndroidRuntime(2338): 	at dalvik.system.DexPathList.findClass(DexPathList.java:338)
10-22 05:25:06.298: E/AndroidRuntime(2338): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
10-22 05:25:06.298: E/AndroidRuntime(2338): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
10-22 05:25:06.298: E/AndroidRuntime(2338): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
10-22 05:25:06.298: E/AndroidRuntime(2338): 	at android.app.ActivityThread.getDexFilesByClassLoader_23(ActivityThread.java:2618)
10-22 05:25:06.298: E/AndroidRuntime(2338): 	at android.app.ActivityThread.-wrap0(ActivityThread.java)
10-22 05:25:06.298: E/AndroidRuntime(2338): 	at android.app.ActivityThread$1.run(ActivityThread.java:2774)
10-22 05:25:06.298: E/AndroidRuntime(2338): 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by hanbinglengyue** [comment]
可以把样本发到我邮箱，我明天试试，edunwu@gmail.com

**Comment by nishuoshenme** [comment]
> 可以把样本发到我邮箱，我明天试试，[edunwu@gmail.com](mailto:edunwu@gmail.com)

我直接留应用宝的链接好了
[link](https://t.cn/Ai3DiY0V)
